// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_windows_at
NumericVector get_windows_at(NumericVector V, int width, IntegerVector x, IntegerVector y, IntegerVector z);
RcppExport SEXP _dl4ni_get_windows_at(SEXP VSEXP, SEXP widthSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(get_windows_at(V, width, x, y, z));
    return rcpp_result_gen;
END_RCPP
}
// results_to_volume
void results_to_volume(NumericVector V, int width, NumericVector res, NumericVector counts, IntegerVector x, IntegerVector y, IntegerVector z);
RcppExport SEXP _dl4ni_results_to_volume(SEXP VSEXP, SEXP widthSEXP, SEXP resSEXP, SEXP countsSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res(resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z(zSEXP);
    results_to_volume(V, width, res, counts, x, y, z);
    return R_NilValue;
END_RCPP
}
// results_to_volume_label
void results_to_volume_label(NumericVector V, int width, NumericVector res, IntegerVector x, IntegerVector y, IntegerVector z);
RcppExport SEXP _dl4ni_results_to_volume_label(SEXP VSEXP, SEXP widthSEXP, SEXP resSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res(resSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z(zSEXP);
    results_to_volume_label(V, width, res, x, y, z);
    return R_NilValue;
END_RCPP
}
// results_to_volume_label_with_distance
void results_to_volume_label_with_distance(NumericVector V, int width, NumericVector res, NumericVector last_distance, IntegerVector x, IntegerVector y, IntegerVector z);
RcppExport SEXP _dl4ni_results_to_volume_label_with_distance(SEXP VSEXP, SEXP widthSEXP, SEXP resSEXP, SEXP last_distanceSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res(resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type last_distance(last_distanceSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z(zSEXP);
    results_to_volume_label_with_distance(V, width, res, last_distance, x, y, z);
    return R_NilValue;
END_RCPP
}
// regularize
NumericVector regularize(NumericVector image, NumericVector kernel);
RcppExport SEXP _dl4ni_regularize(SEXP imageSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type image(imageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(regularize(image, kernel));
    return rcpp_result_gen;
END_RCPP
}
// which_max
NumericVector which_max(NumericVector image);
RcppExport SEXP _dl4ni_which_max(SEXP imageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type image(imageSEXP);
    rcpp_result_gen = Rcpp::wrap(which_max(image));
    return rcpp_result_gen;
END_RCPP
}
// to_categorical_volume_cpp
IntegerVector to_categorical_volume_cpp(NumericVector image, IntegerVector unique_labels);
RcppExport SEXP _dl4ni_to_categorical_volume_cpp(SEXP imageSEXP, SEXP unique_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type image(imageSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type unique_labels(unique_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(to_categorical_volume_cpp(image, unique_labels));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dl4ni_get_windows_at", (DL_FUNC) &_dl4ni_get_windows_at, 5},
    {"_dl4ni_results_to_volume", (DL_FUNC) &_dl4ni_results_to_volume, 7},
    {"_dl4ni_results_to_volume_label", (DL_FUNC) &_dl4ni_results_to_volume_label, 6},
    {"_dl4ni_results_to_volume_label_with_distance", (DL_FUNC) &_dl4ni_results_to_volume_label_with_distance, 7},
    {"_dl4ni_regularize", (DL_FUNC) &_dl4ni_regularize, 2},
    {"_dl4ni_which_max", (DL_FUNC) &_dl4ni_which_max, 1},
    {"_dl4ni_to_categorical_volume_cpp", (DL_FUNC) &_dl4ni_to_categorical_volume_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_dl4ni(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
