# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_windows_at <- function(V, width, x, y, z) {
    .Call('_dl4ni_get_windows_at', PACKAGE = 'dl4ni', V, width, x, y, z)
}

results_to_volume <- function(V, width, res, counts, x, y, z) {
    invisible(.Call('_dl4ni_results_to_volume', PACKAGE = 'dl4ni', V, width, res, counts, x, y, z))
}

results_to_volume_label <- function(V, width, res, x, y, z) {
    invisible(.Call('_dl4ni_results_to_volume_label', PACKAGE = 'dl4ni', V, width, res, x, y, z))
}

results_to_volume_label_with_distance <- function(V, width, res, last_distance, x, y, z) {
    invisible(.Call('_dl4ni_results_to_volume_label_with_distance', PACKAGE = 'dl4ni', V, width, res, last_distance, x, y, z))
}

regularize <- function(image, kernel) {
    .Call('_dl4ni_regularize', PACKAGE = 'dl4ni', image, kernel)
}

